### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by anserran** [adlnet/jxapi#10]
I'd like to use jxapi in a project, is it uploaded to any Maven repository? I saw the project is configured to deploy to Sonatype, but I'm unable to find it there. Thanks!

**Comment by jarrodRiv** [comment]
I have the same question - is this library published to a Maven repo anywhere?

**Comment by ljwolford** [comment]
It currently isn't published to a Maven repo at this point, but we can add it at a later point...hopefully in the beginning of 2016. Sorry, I know that's vague but I just have to find some time to do so.

**Comment by ljwolford** [comment]
Guess I had more time than I thought!

https://search.maven.org/#search%7Cga%7C1%7Cjxapi

**Comment by anserran** [comment]
It works perfectly, thanks!

**Comment by jarrodRiv** [comment]
Yes, thanks very much! :+1:
