### ISSUE TITLE
Issue in using https://github.com/adlnet/jxapi jar

### ISSUE THREAD

**Issue by Rialakshmi** [adlnet/jxapi#23]
in the link given below:
https://github.com/adlnet/jxapi
I have used the jar
Issue 1: String publishedId = client.publishStatement(statement); PublishStatement is not in your Code
Issue 2: I am not able to connect to Learning Locker or Watershed by giving correct LRS End Point and Key(username) and Secret(password)

**Comment by ljwolford** [comment]
Thank you.

Issue 1: We will update the ReadMe. You should use either client.postStatement(statement) or client.putStatement(statement, id)

Issue 2: What error message are you receiving when trying to connect?

**Comment by Rialakshmi** [comment]
Thanks a lot for the quick reply!!!!

I got Unknown Host Error. I checked the same with Learning Locker team,
they provide with new endpoint. I will check and I will update on the same.

**Comment by Rialakshmi** [comment]
Issue 2 is resolved. I am able to connect with the new EndPoint provided by
Learning Locker  and post my xAPI statement to Learning Locker.

This jar is so much of useful. Thanks for Developing! Have a Great Day
Ahead!!

**Comment by ljwolford** [comment]
Great, glad it's helping you out. If you come across any issues please report them here.
