### ISSUE TITLE
how to add in maven project

### ISSUE THREAD

**Issue by Rialakshmi** [adlnet/jxapi#28]
Sir,

Previously i have added jar and used. Now I have Maven project. for that i want to add dependency. Could you please provide me with the detail.

**Comment by ljwolford** [comment]
Hello,

Depending on how your project is setup, you can add it to the `pom.xml` file like so:

```
<dependencies>
    ...
    <dependency>
        <groupId>gov.adlnet</groupId>
        <artifactId>jxapi</artifactId>
        <version>1.0.3</version>
    </dependency>
    ...
</dependencies>
```

I hope that helps.

**Comment by Rialakshmi** [comment]
Thanks! I made the changes
