### ISSUE TITLE
addFilter is not working

### ISSUE THREAD

**Issue by Rialakshmi** [adlnet/jxapi#30]
client.addFilter('context.extensions.yourExtension', 'customExtensionValue').getStatements(); I get the error, addFilter has private access in StatementClient. I am unable to use this functionality

**Comment by ljwolford** [comment]
Hello,

Please try `client.addFilter(context.getExtension(yourExtension), customExtensionValue).getStatements();`. This will generate the path `/xAPI/statements?yourExtension=customExtensionValue` Please note however that this is NOT a valid xAPI query parameter and if you're using a conformant LRS, it will reject the request with an error. This functionality was kept in for a specific use case with a non-conformant LRS.

**Comment by Rialakshmi** [comment]
Hi.. I am unable to use addFilter(context.getExtension(yourExtension), customExtensionValue).getStatements(); i am getting same error.

**Comment by Rialakshmi** [comment]
Thanks. Its working.  StatementResult result=newConnection.addFilter(learningdataFPT, extension.get(learningdataFPT).getAsString()).getStatements(); getStatements does not print all the values in a statement. for  ex.. it prints this much only...
test mailto:test@gmail.com  http://example.com/tested http://example.com/cebeada3-7477-4816-aac6-29183e20cfe0,

But I want all the information like..
{
    "version": "1.0.0",
    "timestamp": "2016-09-26T10:21:53Z",
    "verb": {
        "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/timedout",
        "display": {
            "en-US": "timedout",
            "us": "timedout"
        }
    },
    "actor": {
        "objectType": "Agent",
        "name": "Thilaga",
        "mbox": "mailto:Thilaga@xxxxxx.com"
    },
    "object": {
        "objectType": "Activity",
        "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/Lesson_ID/Lesson1",
        "definition": {
            "moreInfo": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/asdfasdfasdf/asdf",
            "interactionType": "choice",
            "extensions": {
                "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/extension/COURSE_LOCATION": "asdfasdfasdfasdf"
            },
            "choices": [
                {
                    "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/P_NUMBER/sdfasdfasdf ",
                    "description": {
                        "en-US": "sdfasdfasdf"
                    }
                },
                {
                    "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/CLASSROOM/1232323",
                    "description": {
                        "en-US": "1232323"
                    }
                },
                {
                    "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/CAMPUS/EB2",
                    "description": {
                        "en-US": "Campus:EB2"
                    }
                },
                {
                    "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/LESSON_START_DATE/Wed Feb 03 00:00:00 IST 17",
                    "description": {
                        "en-US": "Start_Date:Wed Feb 03 00:00:00 IST 17"
                    }
                },
                {
                    "id": "http://xxxxxx.com/xapi/yyyyyyyyyyy/object/id/LESSON_END_DATE/Wed Feb 03 00:00:00 IST 17",
                    "description": {
                        "en-US": "End_Date:Wed Feb 03 00:00:00 IST 17"
                    }
                }
            ]
        }
    },
    "context": {
        "instructor": {
            "objectType": "Agent",
            "name": "Nagalakshmi",
            "mbox": "mailto:Nagalakshmi@xxxxxx.com"
        }
    },
    "id": "2b4019c8-dd88-41ec-a7df-c8b7570b8141",
    "authority": {
        "objectType": "Agent",
        "name": "New Client",
        "mbox": "mailto:hi@llr.net"
    },
    "stored": "2017-05-31T13:42:16.226700+00:00"
}

**Comment by Rialakshmi** [comment]
Thanks much for your timely help!
